files:
  - source: /**/en_US.*
    ignore:
      - /Slimefun/DynaTech
      - /Slimefun/EcoPower
      - /Slimefun/ElectricSpawners
      - /Slimefun/FoxyMachines
      - /Slimefun/PrivateStorage
      - /Slimefun/Slimefun4
      - /AutoTrasher
    translation: /**/%locale_with_underscore%.%file_extension%
  - source: /**/en_US_messages.*
    translation: /**/%locale_with_underscore%_messages.%file_extension%
  - source: /**/en_US_config.*
    translation: /**/%locale_with_underscore%_config.%file_extension%
  - source: /DiscordSRV/en_US_linking.*
    translation: /DiscordSRV/%locale_with_underscore%_linking.%file_extension%
  - source: /DiscordSRV/en_US_synchronization.*
    translation: /DiscordSRV/%locale_with_underscore%_synchronization.%file_extension%
  - source: /RealisticSeasons/en_US_temperature.*
    translation: /RealisticSeasons/%locale_with_underscore%_temperature.%file_extension%
