name: Autosquash
on:
  check_run:
    types:
      - completed
  pull_request:
    types:
      - closed
      - labeled
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  autosquash:
    name: Autosquash
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/autosquash@v2
        with:
          github_token: ${{ secrets.AUTOSQUASH_TOKEN }}
          label: Suqash