name: Discord Webhook

on:
  push:
    branches:
    - main

jobs:
  sendwebhook:

    name: Send Webhook
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Discord Webhook
      uses: Mist3r-Robot/classic-discord-webhook@master
      with:
        id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
